pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials') // Jenkins secret ID
        KUBECONFIG_CREDENTIALS = credentials('eks-kubeconfig') // Jenkins secret ID
        IMAGE_NAME = "ananyaj1230@gmail.com/my-app"
        IMAGE_TAG = "v1"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ananyajagdish/devops-capstone.git'
            }
        }
        stage('Test') {
            steps {
                export PYTHONPATH=$(pwd)/app/src
                sh '''
                    python3 -m venv venv
                    source venv/bin/activate
                    pip install pytest
                    pytest
                '''
                sh 'pytest app/tests/test_app.py'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} ."
            }
        }
    }

    post {
        always {
            echo "Pipeline finished. Check build logs for details."
        }
    }
}
