pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-cred-id') // Jenkins secret ID
        KUBECONFIG_CREDENTIALS = credentials('kubeconfig-cred-id') // Jenkins secret ID
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ananyajagdish/devops-capstone.git'
            }
        }
        stage('Test') {
            steps {
                sh 'pytest tests/'
            }
    }

    post {
        always {
            echo "Pipeline finished. Check build logs for details."
        }
    }
}
