pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials') // Jenkins secret ID
        KUBECONFIG_CREDENTIALS = credentials('eks-kubeconfig') // Jenkins secret ID
        IMAGE_NAME = "ananyaj1230/my-app"
        IMAGE_TAG = "v1"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/ananyajagdish/devops-capstone.git'
            }
        }
        stage('Test') {
            steps {
                sh '''
                # Set Python path to find modules
                export PYTHONPATH=$WORKSPACE/app
                python3 -m venv venv
                source venv/bin/activate
                pip install pytest
                pip install flask
                python3 -m pytest devopscapstone/app/tests/
                '''
            }
        }
        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${IMAGE_NAME}:${IMAGE_TAG} -f devopscapstone/docker/Dockerfile ."
            }
        }
    }

    post {
        always {
            echo "Pipeline finished. Check build logs for details."
        }
    }
}
